fix SQS Flag Shop scenario
RhinoSecurityLabs/cloudgoat pull request #276
Opened 2024-11-01 18:22 UTC by jdearmas

#### Overview of Changes
This commit:
- Configures the AWS resources to operate within a Virtual Private Cloud
  - This restricts access to the resources to only the specified IP addresses.
- The web server files are decompressed.
  - This allows greater visibility into the files that are being served.

2024-11-01 19:12 UTC, andrew-aiken requested changes
Few changes, see comments

There are also some resources that probably can get removed (`local_file.sql_file`) and formatting that should be applied. But I can take on that at some point.

2024-11-01 19:51 UTC, andrew-aiken reviewed
There seems to be also an issue with the updated lambda function code. Getting this error when trying to configure the charge amount following the cheat sheet

```
aws sqs send-message --queue-url https://sqs.us-east-1.amazonaws.com/0123456789/cash_charging_queue --message-body '{"charge_amount": 100000000}'
```

<img width="1398" alt="image" src="https://github.com/user-attachments/assets/f7caa3b5-3a5d-4c3f-af9b-3fde90446f47">

2024-11-01 19:53 UTC, andrew-aiken commented on scenarios/sqs_flag_shop/terraform/source/flask/templates/index.html
> +<!--  https://github.com/BoB12-C-G-V/FLAG-Shop -->
This also should probably point to CloudGoat source code since the Lambda function code is changing

2024-11-02 13:21 UTC, andrew-aiken commented
Was able to complete the scenario with that fix

2024-11-04 15:40 UTC, TeneBrae93 approved these changes
Confirmed the full scenario now works as intended -- including the allow-listing on the web server.

2024-11-04 15:41 UTC, merged

2024-11-04 20:41 UTC, andrew-aiken commented
I'll look into opening a new pull request to implement the code changes I suggested